server:
  port: 8080

spring:
  profiles:
    active: dev

  application:
    name: DogPath-Backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dogpath
    username: root
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true